<?php

/**
 * PluginI18NItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginI18NItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return PluginI18NItemTable The table instance
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginI18NItem');
    }
}